name: Publish preview update

on:
  schedule:
    - cron: "0 0 * * *" # Runs at midnight every day
  push:
    branches:
      - "*"

jobs:
  publish_preview_update:
    name: Publish preview update
    type: update
    params:
      branch: ${{ github.ref_name || 'test' }}
