name: Publish preview update

# Disabling while upgrading to Expo 54
# on:
#   push:
#     branches:
#       - "*"

jobs:
  publish_preview_update:
    name: Publish preview update
    type: update
    params:
      branch: ${{ github.ref_name || 'test' }}
